### ISSUE TITLE
Fluid system completely broken

### ISSUE THREAD

**Issue by VoidLeech** [petrolpark/Petrols-Parts#23]
**Describe the bug**

The entire fluid system is broken. Right clicking tanks doesn't fill them, emptying recipes never progress past turning the item upside down, pumps produce particles but never actually move fluids. There's probably more. This wasn't the case with version 1.0.3

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Build the setup in the attached video
2. Toss water bucket on drain

**Expected Behavior**

It all to work :p

**Screenshots**

https://github.com/user-attachments/assets/82f6446c-518a-49bb-94cf-9567c64ecad9

**System Information**

- Forge 47.3.0
- Create 0.5.1j
- Petrol's Parts 1.1.2
- Petrolpark 1.2.1 (1.2.2 crashes)

**Additional context**

This mixin seems *incredibly* suspect to me. https://github.com/petrolpark/Create-Library/blob/d19af8d3c82627939444127378049d51f7189217/src/main/java/com/petrolpark/mixin/compat/create/FluidTankMixin.java#L20-L29

**Comment by MineveraMacDougal** [comment]
I can confirm this issue with the above versions. I am a participant of a game server and immediately got to troubleshooting after a massive update to solve an unrelated issue.

**Comment by Pacionist** [comment]
I can confirm this issue with the above versions too. Spout also doesn't filling up. The problem also reproduce itself when you install only petrolpark library.

**Comment by VoidLeech** [comment]
Quoting a user from Curseforge here:
> Having this mod + Its library installed, breaks the tile entities in Tinkers construct.
Blocks such as the Melter become unusable and complain about never having enough space.
Not sure why this mod would conflict with Tcon's tile entities, and since I don't see a github I'm reporting it here. Cheers.

Having just the library mod and Create installed (basically guaranteed as the library is only for Create addons) is enough to break not just Create's entire fluid system (which is bad enough; I'm seeing more than a couple support questions related to it in the Create discord per day, but at least we know the cause and can point people to removing/downgrading the mod), but *also* that of other mods which might not have that luxury.

Would really appreciate an acknowledgement of the issue because this is quite serious. There's gotta be a better mixin available for your use case.

**Comment by petrolpark** [comment]
Fixed in 1.2.2 of the library. That crashing is a separate issue.

**Comment by VoidLeech** [comment]
Still broken with library 1.3.2. It now voids fluids if it's trying to fill to somewhere that already has a different fluid.

https://github.com/user-attachments/assets/9ebdd5c0-97de-4111-b1e1-1e4c137ab04c
