### ISSUE TITLE
Game crash with CTM analogue

### ISSUE THREAD

**Issue by AShu7SPb** [petrolpark/Petrols-Parts#65]
1.21.1 neoforge

It is impossible to open and create a new world using the "continuity" mod and its mandatory ones.

Install Continuity, ConnectorExtass... and the rest.
Install the petrolspark mod, petrolspart.
Start the game.
Attempt to open a world.
Attempt to create a new world.

Expected Behavior is:

The world has opened and the mod elements are working.

without petrols mod is still works

---------

Without "Petrol" game with ctm is works.
Without ctm game with "Petrol" is works.

1) installed mods

2) try to open world

![Image](https://github.com/user-attachments/assets/04e1898e-ed44-46eb-817c-691a6a7285e1)

![Image](https://github.com/user-attachments/assets/2949e21a-945f-4804-9151-81da0b985d41)

**Comment by petrolpark** [comment]
Please attach the debug.log

**Comment by AShu7SPb** [comment]
here it is

[tl-logger13116059550525684655.txt](https://github.com/user-attachments/files/20030172/tl-logger13116059550525684655.txt)

**Comment by kil0byt3** [comment]
experiencing same issue

**Comment by AShu7SPb** [comment]
@kil0byt3 Well, you can show your crash log

**Comment by AShu7SPb** [comment]
well. i install newer version of forgified fabric api and game is not crashes "107 2.0.26" @kil0byt3 

maybe the problem is solved..?

**Comment by kil0byt3** [comment]
Negative. I was on that version and still having issues. I updated to Forgified Fabric API 0.115.6 2.1.0 and still have the issue. 

Debug log of game start, world load and datapack issue: https://mclo.gs/JlwMi2p

Due to mclo.gs restrictions, some of the middle lines had to be cut. It should still have the initial lines and ending lines

**Comment by Galexion** [comment]
~~I think I narrowed it down~~

scratch that.

https://mclo.gs/9IiVZnt
Log ends when I reach the "Safe Mode" screen.

**Comment by Galexion** [comment]
Alright, I Completely disabled both FF API and Connector & it's dependencies, and I am still having a crash.

for reference here is my Mod List.
https://pastebin.com/HL2A4zpS

https://mclo.gs/MRw5OEv

**Comment by AShu7SPb** [comment]
Do you use connectorextass?

**Comment by AShu7SPb** [comment]
now installed mod is here

neoforge 21.1.145

![Image](https://github.com/user-attachments/assets/92bc6128-0d6e-4f62-818d-ce30d214dcec)
