### ISSUE TITLE
Pneumatic tube and hydraulic transmission duplication bug

### ISSUE THREAD

**Issue by Derpgamer22** [petrolpark/Petrols-Parts#81]
**Describe the bug**

When you break the tubes that connect the Pneumatic tubes and hydraulic transmissions together, they will drop more that what was used to connect them. An example would be using 5 pneumatic tubes to connect the two ends together and getting like 7 back when you break just the connecting pipe. For the hydraulic transmission, it be like using 14 to connect together, and getting like 45 back when breaking the pipe.

 - Create 6.0.6
- Petrol Parts 1.2.3

**Comment by petrolpark** [comment]
What version of the library are you using?

**Comment by Derpgamer22** [comment]
1.4.9

just updated to mod to the newest version just now of this message being typed, so I can check if it still is bugged

**Comment by Derpgamer22** [comment]
yeah still does the glitch in 1.4.11

**Comment by Alexandra-Myers** [comment]
I'm actually seeing the opposite issue in the same versions as was listed here. I started off with 14 hydraulic tubes in my inventory and made a connection using all of them, and no matter what method I used to break them, it would only give back 4...

**Comment by Derpgamer22** [comment]
interesting

**Comment by petrolpark** [comment]
Fixed in 1.4.15 of the Library.

**Comment by Derpgamer22** [comment]
Hey this bug still persists in the 1.20.1 version. Do you think you can fix it in there?

**Comment by LornestFluke** [comment]
Having the same issue in 1.20.1, no matter what method is used to break Hydraulic Transmissions they will only ever return a total of 4.
